<?php

/**
* Inheritance: no
* Variants: no


Fields Summary:
- offernumber [input]
- dateCreated [datetime]
- dateValidUntil [date]
- totalPriceBeforeDiscount [numeric]
- totalPrice [numeric]
- discountType [select]
- discount [numeric]
- cartId [input]
- items [manyToManyObjectRelation]
- customItems [manyToManyObjectRelation]
*/


return Pimcore\Model\DataObject\ClassDefinition::__set_state(array(
   'id' => 'EF_OTO',
   'name' => 'OfferToolOffer',
   'description' => '',
   'creationDate' => 0,
   'modificationDate' => 1643025788,
   'userOwner' => 0,
   'userModification' => 1,
   'parentClass' => '',
   'implementsInterfaces' => '',
   'listingParentClass' => '',
   'useTraits' => '',
   'listingUseTraits' => '',
   'encryption' => false,
   'encryptedTables' => 
  array (
  ),
   'allowInherit' => false,
   'allowVariants' => false,
   'showVariants' => false,
   'fieldDefinitions' => 
  array (
  ),
   'layoutDefinitions' => 
  Pimcore\Model\DataObject\ClassDefinition\Layout\Panel::__set_state(array(
     'fieldtype' => 'panel',
     'layout' => NULL,
     'border' => false,
     'name' => 'pimcore_root',
     'type' => NULL,
     'region' => NULL,
     'title' => NULL,
     'width' => 0,
     'height' => 0,
     'collapsible' => false,
     'collapsed' => false,
     'bodyStyle' => NULL,
     'datatype' => 'layout',
     'permissions' => NULL,
     'childs' => 
    array (
      0 => 
      Pimcore\Model\DataObject\ClassDefinition\Layout\Tabpanel::__set_state(array(
         'fieldtype' => 'tabpanel',
         'border' => false,
         'tabPosition' => 'top',
         'name' => 'Layout',
         'type' => NULL,
         'region' => NULL,
         'title' => NULL,
         'width' => NULL,
         'height' => NULL,
         'collapsible' => false,
         'collapsed' => false,
         'bodyStyle' => NULL,
         'datatype' => 'layout',
         'permissions' => NULL,
         'childs' => 
        array (
          0 => 
          Pimcore\Model\DataObject\ClassDefinition\Layout\Panel::__set_state(array(
             'fieldtype' => 'panel',
             'layout' => '',
             'border' => false,
             'name' => 'General',
             'type' => '',
             'region' => 'center',
             'title' => 'General',
             'width' => NULL,
             'height' => NULL,
             'collapsible' => false,
             'collapsed' => false,
             'bodyStyle' => '',
             'datatype' => 'layout',
             'permissions' => '',
             'childs' => 
            array (
              0 => 
              Pimcore\Model\DataObject\ClassDefinition\Layout\Text::__set_state(array(
                 'fieldtype' => 'text',
                 'html' => '<b>OfferToolOffer </b>as storage for created offers in the frontend.&nbsp;May be extended for specific use case.&nbsp;',
                 'renderingClass' => NULL,
                 'renderingData' => NULL,
                 'border' => false,
                 'name' => 'Layout',
                 'type' => NULL,
                 'region' => NULL,
                 'title' => '',
                 'width' => NULL,
                 'height' => NULL,
                 'collapsible' => false,
                 'collapsed' => false,
                 'bodyStyle' => 'padding: 10px; background-color: #d9edf7; border-color: #bce8f1 !important; color: #31708f;',
                 'datatype' => 'layout',
                 'permissions' => NULL,
                 'childs' => 
                array (
                ),
                 'locked' => false,
                 'blockedVarsForExport' => 
                array (
                ),
              )),
              1 => 
              Pimcore\Model\DataObject\ClassDefinition\Layout\Fieldset::__set_state(array(
                 'fieldtype' => 'fieldset',
                 'name' => 'Basic',
                 'type' => NULL,
                 'region' => NULL,
                 'title' => 'Basic',
                 'width' => NULL,
                 'height' => NULL,
                 'collapsible' => false,
                 'collapsed' => false,
                 'bodyStyle' => '',
                 'datatype' => 'layout',
                 'permissions' => NULL,
                 'childs' => 
                array (
                  0 => 
                  Pimcore\Model\DataObject\ClassDefinition\Data\Input::__set_state(array(
                     'fieldtype' => 'input',
                     'width' => 400,
                     'defaultValue' => NULL,
                     'columnLength' => 255,
                     'regex' => '',
                     'unique' => NULL,
                     'showCharCount' => NULL,
                     'name' => 'offernumber',
                     'title' => 'Offernumber',
                     'tooltip' => '',
                     'mandatory' => false,
                     'noteditable' => false,
                     'index' => false,
                     'locked' => false,
                     'style' => '',
                     'permissions' => '',
                     'datatype' => 'data',
                     'relationType' => false,
                     'invisible' => false,
                     'visibleGridView' => false,
                     'visibleSearch' => false,
                     'forbiddenNames' => 
                    array (
                      0 => 'id',
                      1 => 'key',
                      2 => 'path',
                      3 => 'type',
                      4 => 'index',
                      5 => 'classname',
                      6 => 'creationdate',
                      7 => 'userowner',
                      8 => 'value',
                      9 => 'class',
                      10 => 'list',
                      11 => 'fullpath',
                      12 => 'childs',
                      13 => 'values',
                      14 => 'cachetag',
                      15 => 'cachetags',
                      16 => 'parent',
                      17 => 'published',
                      18 => 'valuefromparent',
                      19 => 'userpermissions',
                      20 => 'dependencies',
                      21 => 'modificationdate',
                      22 => 'usermodification',
                      23 => 'byid',
                      24 => 'bypath',
                      25 => 'data',
                      26 => 'versions',
                      27 => 'properties',
                      28 => 'permissions',
                      29 => 'permissionsforuser',
                      30 => 'childamount',
                      31 => 'apipluginbroker',
                      32 => 'resource',
                      33 => 'parentClass',
                      34 => 'definition',
                      35 => 'locked',
                      36 => 'language',
                      37 => 'omitmandatorycheck',
                      38 => 'idpath',
                      39 => 'object',
                      40 => 'fieldname',
                      41 => 'property',
                      42 => 'parentid',
                      43 => 'children',
                      44 => 'scheduledtasks',
                    ),
                     'blockedVarsForExport' => 
                    array (
                    ),
                     'defaultValueGenerator' => '',
                  )),
                  1 => 
                  Pimcore\Model\DataObject\ClassDefinition\Data\Datetime::__set_state(array(
                     'fieldtype' => 'datetime',
                     'queryColumnType' => 'bigint(20)',
                     'columnType' => 'bigint(20)',
                     'defaultValue' => NULL,
                     'useCurrentDate' => false,
                     'name' => 'dateCreated',
                     'title' => 'CreationDate',
                     'tooltip' => '',
                     'mandatory' => false,
                     'noteditable' => false,
                     'index' => false,
                     'locked' => false,
                     'style' => '',
                     'permissions' => '',
                     'datatype' => 'data',
                     'relationType' => false,
                     'invisible' => false,
                     'visibleGridView' => false,
                     'visibleSearch' => false,
                     'forbiddenNames' => 
                    array (
                      0 => 'id',
                      1 => 'key',
                      2 => 'path',
                      3 => 'type',
                      4 => 'index',
                      5 => 'classname',
                      6 => 'creationdate',
                      7 => 'userowner',
                      8 => 'value',
                      9 => 'class',
                      10 => 'list',
                      11 => 'fullpath',
                      12 => 'childs',
                      13 => 'values',
                      14 => 'cachetag',
                      15 => 'cachetags',
                      16 => 'parent',
                      17 => 'published',
                      18 => 'valuefromparent',
                      19 => 'userpermissions',
                      20 => 'dependencies',
                      21 => 'modificationdate',
                      22 => 'usermodification',
                      23 => 'byid',
                      24 => 'bypath',
                      25 => 'data',
                      26 => 'versions',
                      27 => 'properties',
                      28 => 'permissions',
                      29 => 'permissionsforuser',
                      30 => 'childamount',
                      31 => 'apipluginbroker',
                      32 => 'resource',
                      33 => 'parentClass',
                      34 => 'definition',
                      35 => 'locked',
                      36 => 'language',
                      37 => 'omitmandatorycheck',
                      38 => 'idpath',
                      39 => 'object',
                      40 => 'fieldname',
                      41 => 'property',
                      42 => 'parentid',
                      43 => 'children',
                      44 => 'scheduledtasks',
                    ),
                     'blockedVarsForExport' => 
                    array (
                    ),
                     'defaultValueGenerator' => '',
                  )),
                  2 => 
                  Pimcore\Model\DataObject\ClassDefinition\Data\Date::__set_state(array(
                     'fieldtype' => 'date',
                     'queryColumnType' => 'bigint(20)',
                     'columnType' => 'bigint(20)',
                     'defaultValue' => NULL,
                     'useCurrentDate' => false,
                     'name' => 'dateValidUntil',
                     'title' => 'Valid Until',
                     'tooltip' => '',
                     'mandatory' => false,
                     'noteditable' => false,
                     'index' => false,
                     'locked' => false,
                     'style' => '',
                     'permissions' => NULL,
                     'datatype' => 'data',
                     'relationType' => false,
                     'invisible' => false,
                     'visibleGridView' => false,
                     'visibleSearch' => false,
                     'forbiddenNames' => 
                    array (
                      0 => 'id',
                      1 => 'key',
                      2 => 'path',
                      3 => 'type',
                      4 => 'index',
                      5 => 'classname',
                      6 => 'creationdate',
                      7 => 'userowner',
                      8 => 'value',
                      9 => 'class',
                      10 => 'list',
                      11 => 'fullpath',
                      12 => 'childs',
                      13 => 'values',
                      14 => 'cachetag',
                      15 => 'cachetags',
                      16 => 'parent',
                      17 => 'published',
                      18 => 'valuefromparent',
                      19 => 'userpermissions',
                      20 => 'dependencies',
                      21 => 'modificationdate',
                      22 => 'usermodification',
                      23 => 'byid',
                      24 => 'bypath',
                      25 => 'data',
                      26 => 'versions',
                      27 => 'properties',
                      28 => 'permissions',
                      29 => 'permissionsforuser',
                      30 => 'childamount',
                      31 => 'apipluginbroker',
                      32 => 'resource',
                      33 => 'parentClass',
                      34 => 'definition',
                      35 => 'locked',
                      36 => 'language',
                      37 => 'omitmandatorycheck',
                      38 => 'idpath',
                      39 => 'object',
                      40 => 'fieldname',
                      41 => 'property',
                      42 => 'parentid',
                      43 => 'children',
                      44 => 'scheduledtasks',
                    ),
                     'blockedVarsForExport' => 
                    array (
                    ),
                     'defaultValueGenerator' => '',
                  )),
                ),
                 'locked' => false,
                 'blockedVarsForExport' => 
                array (
                ),
                 'labelWidth' => 100,
                 'labelAlign' => 'left',
              )),
              2 => 
              Pimcore\Model\DataObject\ClassDefinition\Layout\Fieldset::__set_state(array(
                 'fieldtype' => 'fieldset',
                 'name' => 'Price Informations',
                 'type' => NULL,
                 'region' => NULL,
                 'title' => 'Price Informations',
                 'width' => NULL,
                 'height' => NULL,
                 'collapsible' => false,
                 'collapsed' => false,
                 'bodyStyle' => '',
                 'datatype' => 'layout',
                 'permissions' => NULL,
                 'childs' => 
                array (
                  0 => 
                  Pimcore\Model\DataObject\ClassDefinition\Data\Numeric::__set_state(array(
                     'fieldtype' => 'numeric',
                     'width' => 400,
                     'defaultValue' => NULL,
                     'integer' => false,
                     'unsigned' => false,
                     'minValue' => NULL,
                     'maxValue' => NULL,
                     'unique' => NULL,
                     'decimalSize' => 19,
                     'decimalPrecision' => 4,
                     'name' => 'totalPriceBeforeDiscount',
                     'title' => 'Total Price Before Discount',
                     'tooltip' => '',
                     'mandatory' => false,
                     'noteditable' => false,
                     'index' => false,
                     'locked' => false,
                     'style' => '',
                     'permissions' => NULL,
                     'datatype' => 'data',
                     'relationType' => false,
                     'invisible' => false,
                     'visibleGridView' => false,
                     'visibleSearch' => false,
                     'forbiddenNames' => 
                    array (
                      0 => 'id',
                      1 => 'key',
                      2 => 'path',
                      3 => 'type',
                      4 => 'index',
                      5 => 'classname',
                      6 => 'creationdate',
                      7 => 'userowner',
                      8 => 'value',
                      9 => 'class',
                      10 => 'list',
                      11 => 'fullpath',
                      12 => 'childs',
                      13 => 'values',
                      14 => 'cachetag',
                      15 => 'cachetags',
                      16 => 'parent',
                      17 => 'published',
                      18 => 'valuefromparent',
                      19 => 'userpermissions',
                      20 => 'dependencies',
                      21 => 'modificationdate',
                      22 => 'usermodification',
                      23 => 'byid',
                      24 => 'bypath',
                      25 => 'data',
                      26 => 'versions',
                      27 => 'properties',
                      28 => 'permissions',
                      29 => 'permissionsforuser',
                      30 => 'childamount',
                      31 => 'apipluginbroker',
                      32 => 'resource',
                      33 => 'parentClass',
                      34 => 'definition',
                      35 => 'locked',
                      36 => 'language',
                      37 => 'omitmandatorycheck',
                      38 => 'idpath',
                      39 => 'object',
                      40 => 'fieldname',
                      41 => 'property',
                      42 => 'parentid',
                      43 => 'children',
                      44 => 'scheduledtasks',
                    ),
                     'blockedVarsForExport' => 
                    array (
                    ),
                     'defaultValueGenerator' => '',
                  )),
                  1 => 
                  Pimcore\Model\DataObject\ClassDefinition\Data\Numeric::__set_state(array(
                     'fieldtype' => 'numeric',
                     'width' => 400,
                     'defaultValue' => NULL,
                     'integer' => false,
                     'unsigned' => false,
                     'minValue' => NULL,
                     'maxValue' => NULL,
                     'unique' => NULL,
                     'decimalSize' => 19,
                     'decimalPrecision' => 4,
                     'name' => 'totalPrice',
                     'title' => 'TotalPrice',
                     'tooltip' => '',
                     'mandatory' => false,
                     'noteditable' => false,
                     'index' => false,
                     'locked' => false,
                     'style' => '',
                     'permissions' => '',
                     'datatype' => 'data',
                     'relationType' => false,
                     'invisible' => false,
                     'visibleGridView' => false,
                     'visibleSearch' => false,
                     'forbiddenNames' => 
                    array (
                      0 => 'id',
                      1 => 'key',
                      2 => 'path',
                      3 => 'type',
                      4 => 'index',
                      5 => 'classname',
                      6 => 'creationdate',
                      7 => 'userowner',
                      8 => 'value',
                      9 => 'class',
                      10 => 'list',
                      11 => 'fullpath',
                      12 => 'childs',
                      13 => 'values',
                      14 => 'cachetag',
                      15 => 'cachetags',
                      16 => 'parent',
                      17 => 'published',
                      18 => 'valuefromparent',
                      19 => 'userpermissions',
                      20 => 'dependencies',
                      21 => 'modificationdate',
                      22 => 'usermodification',
                      23 => 'byid',
                      24 => 'bypath',
                      25 => 'data',
                      26 => 'versions',
                      27 => 'properties',
                      28 => 'permissions',
                      29 => 'permissionsforuser',
                      30 => 'childamount',
                      31 => 'apipluginbroker',
                      32 => 'resource',
                      33 => 'parentClass',
                      34 => 'definition',
                      35 => 'locked',
                      36 => 'language',
                      37 => 'omitmandatorycheck',
                      38 => 'idpath',
                      39 => 'object',
                      40 => 'fieldname',
                      41 => 'property',
                      42 => 'parentid',
                      43 => 'children',
                      44 => 'scheduledtasks',
                    ),
                     'blockedVarsForExport' => 
                    array (
                    ),
                     'defaultValueGenerator' => '',
                  )),
                  2 => 
                  Pimcore\Model\DataObject\ClassDefinition\Data\Select::__set_state(array(
                     'fieldtype' => 'select',
                     'options' => 
                    array (
                      0 => 
                      array (
                        'key' => 'Percent',
                        'value' => 'percent',
                      ),
                      1 => 
                      array (
                        'key' => 'Amount',
                        'value' => 'amount',
                      ),
                    ),
                     'width' => 400,
                     'defaultValue' => '',
                     'optionsProviderClass' => NULL,
                     'optionsProviderData' => NULL,
                     'columnLength' => 190,
                     'dynamicOptions' => false,
                     'name' => 'discountType',
                     'title' => 'Discount Type',
                     'tooltip' => '',
                     'mandatory' => false,
                     'noteditable' => false,
                     'index' => false,
                     'locked' => false,
                     'style' => '',
                     'permissions' => NULL,
                     'datatype' => 'data',
                     'relationType' => false,
                     'invisible' => false,
                     'visibleGridView' => false,
                     'visibleSearch' => false,
                     'forbiddenNames' => 
                    array (
                      0 => 'id',
                      1 => 'key',
                      2 => 'path',
                      3 => 'type',
                      4 => 'index',
                      5 => 'classname',
                      6 => 'creationdate',
                      7 => 'userowner',
                      8 => 'value',
                      9 => 'class',
                      10 => 'list',
                      11 => 'fullpath',
                      12 => 'childs',
                      13 => 'values',
                      14 => 'cachetag',
                      15 => 'cachetags',
                      16 => 'parent',
                      17 => 'published',
                      18 => 'valuefromparent',
                      19 => 'userpermissions',
                      20 => 'dependencies',
                      21 => 'modificationdate',
                      22 => 'usermodification',
                      23 => 'byid',
                      24 => 'bypath',
                      25 => 'data',
                      26 => 'versions',
                      27 => 'properties',
                      28 => 'permissions',
                      29 => 'permissionsforuser',
                      30 => 'childamount',
                      31 => 'apipluginbroker',
                      32 => 'resource',
                      33 => 'parentClass',
                      34 => 'definition',
                      35 => 'locked',
                      36 => 'language',
                      37 => 'omitmandatorycheck',
                      38 => 'idpath',
                      39 => 'object',
                      40 => 'fieldname',
                      41 => 'property',
                      42 => 'parentid',
                      43 => 'children',
                      44 => 'scheduledtasks',
                    ),
                     'blockedVarsForExport' => 
                    array (
                    ),
                     'defaultValueGenerator' => '',
                  )),
                  3 => 
                  Pimcore\Model\DataObject\ClassDefinition\Data\Numeric::__set_state(array(
                     'fieldtype' => 'numeric',
                     'width' => 400,
                     'defaultValue' => NULL,
                     'integer' => false,
                     'unsigned' => false,
                     'minValue' => NULL,
                     'maxValue' => NULL,
                     'unique' => NULL,
                     'decimalSize' => 19,
                     'decimalPrecision' => 4,
                     'name' => 'discount',
                     'title' => 'Discount',
                     'tooltip' => '',
                     'mandatory' => false,
                     'noteditable' => false,
                     'index' => false,
                     'locked' => false,
                     'style' => '',
                     'permissions' => NULL,
                     'datatype' => 'data',
                     'relationType' => false,
                     'invisible' => false,
                     'visibleGridView' => false,
                     'visibleSearch' => false,
                     'forbiddenNames' => 
                    array (
                      0 => 'id',
                      1 => 'key',
                      2 => 'path',
                      3 => 'type',
                      4 => 'index',
                      5 => 'classname',
                      6 => 'creationdate',
                      7 => 'userowner',
                      8 => 'value',
                      9 => 'class',
                      10 => 'list',
                      11 => 'fullpath',
                      12 => 'childs',
                      13 => 'values',
                      14 => 'cachetag',
                      15 => 'cachetags',
                      16 => 'parent',
                      17 => 'published',
                      18 => 'valuefromparent',
                      19 => 'userpermissions',
                      20 => 'dependencies',
                      21 => 'modificationdate',
                      22 => 'usermodification',
                      23 => 'byid',
                      24 => 'bypath',
                      25 => 'data',
                      26 => 'versions',
                      27 => 'properties',
                      28 => 'permissions',
                      29 => 'permissionsforuser',
                      30 => 'childamount',
                      31 => 'apipluginbroker',
                      32 => 'resource',
                      33 => 'parentClass',
                      34 => 'definition',
                      35 => 'locked',
                      36 => 'language',
                      37 => 'omitmandatorycheck',
                      38 => 'idpath',
                      39 => 'object',
                      40 => 'fieldname',
                      41 => 'property',
                      42 => 'parentid',
                      43 => 'children',
                      44 => 'scheduledtasks',
                    ),
                     'blockedVarsForExport' => 
                    array (
                    ),
                     'defaultValueGenerator' => '',
                  )),
                ),
                 'locked' => false,
                 'blockedVarsForExport' => 
                array (
                ),
                 'labelWidth' => 100,
                 'labelAlign' => 'left',
              )),
              3 => 
              Pimcore\Model\DataObject\ClassDefinition\Layout\Fieldset::__set_state(array(
                 'fieldtype' => 'fieldset',
                 'name' => 'System Informations',
                 'type' => NULL,
                 'region' => NULL,
                 'title' => 'System Informations',
                 'width' => NULL,
                 'height' => NULL,
                 'collapsible' => true,
                 'collapsed' => true,
                 'bodyStyle' => '',
                 'datatype' => 'layout',
                 'permissions' => NULL,
                 'childs' => 
                array (
                  0 => 
                  Pimcore\Model\DataObject\ClassDefinition\Data\Input::__set_state(array(
                     'fieldtype' => 'input',
                     'width' => '',
                     'defaultValue' => NULL,
                     'columnLength' => 255,
                     'regex' => '',
                     'unique' => NULL,
                     'showCharCount' => NULL,
                     'name' => 'cartId',
                     'title' => 'Cart Id',
                     'tooltip' => '',
                     'mandatory' => false,
                     'noteditable' => false,
                     'index' => false,
                     'locked' => false,
                     'style' => '',
                     'permissions' => NULL,
                     'datatype' => 'data',
                     'relationType' => false,
                     'invisible' => false,
                     'visibleGridView' => false,
                     'visibleSearch' => false,
                     'forbiddenNames' => 
                    array (
                      0 => 'id',
                      1 => 'key',
                      2 => 'path',
                      3 => 'type',
                      4 => 'index',
                      5 => 'classname',
                      6 => 'creationdate',
                      7 => 'userowner',
                      8 => 'value',
                      9 => 'class',
                      10 => 'list',
                      11 => 'fullpath',
                      12 => 'childs',
                      13 => 'values',
                      14 => 'cachetag',
                      15 => 'cachetags',
                      16 => 'parent',
                      17 => 'published',
                      18 => 'valuefromparent',
                      19 => 'userpermissions',
                      20 => 'dependencies',
                      21 => 'modificationdate',
                      22 => 'usermodification',
                      23 => 'byid',
                      24 => 'bypath',
                      25 => 'data',
                      26 => 'versions',
                      27 => 'properties',
                      28 => 'permissions',
                      29 => 'permissionsforuser',
                      30 => 'childamount',
                      31 => 'apipluginbroker',
                      32 => 'resource',
                      33 => 'parentClass',
                      34 => 'definition',
                      35 => 'locked',
                      36 => 'language',
                      37 => 'omitmandatorycheck',
                      38 => 'idpath',
                      39 => 'object',
                      40 => 'fieldname',
                      41 => 'property',
                      42 => 'parentid',
                      43 => 'children',
                      44 => 'scheduledtasks',
                    ),
                     'blockedVarsForExport' => 
                    array (
                    ),
                     'defaultValueGenerator' => '',
                  )),
                ),
                 'locked' => false,
                 'blockedVarsForExport' => 
                array (
                ),
                 'labelWidth' => 100,
                 'labelAlign' => 'left',
              )),
            ),
             'locked' => false,
             'blockedVarsForExport' => 
            array (
            ),
             'icon' => NULL,
             'labelWidth' => 100,
             'labelAlign' => 'left',
          )),
          1 => 
          Pimcore\Model\DataObject\ClassDefinition\Layout\Panel::__set_state(array(
             'fieldtype' => 'panel',
             'layout' => NULL,
             'border' => false,
             'name' => 'Items',
             'type' => NULL,
             'region' => NULL,
             'title' => 'Items',
             'width' => NULL,
             'height' => NULL,
             'collapsible' => false,
             'collapsed' => false,
             'bodyStyle' => '',
             'datatype' => 'layout',
             'permissions' => NULL,
             'childs' => 
            array (
              0 => 
              Pimcore\Model\DataObject\ClassDefinition\Data\ManyToManyObjectRelation::__set_state(array(
                 'fieldtype' => 'manyToManyObjectRelation',
                 'width' => '',
                 'height' => '',
                 'maxItems' => '',
                 'relationType' => true,
                 'visibleFields' => NULL,
                 'allowToCreateNewObject' => true,
                 'optimizedAdminLoading' => false,
                 'enableTextSelection' => false,
                 'visibleFieldDefinitions' => 
                array (
                ),
                 'classes' => 
                array (
                  0 => 
                  array (
                    'classes' => 'OfferToolOfferItem',
                  ),
                ),
                 'pathFormatterClass' => NULL,
                 'name' => 'items',
                 'title' => 'Items',
                 'tooltip' => '',
                 'mandatory' => false,
                 'noteditable' => false,
                 'index' => false,
                 'locked' => false,
                 'style' => '',
                 'permissions' => '',
                 'datatype' => 'data',
                 'invisible' => false,
                 'visibleGridView' => false,
                 'visibleSearch' => false,
                 'forbiddenNames' => 
                array (
                  0 => 'id',
                  1 => 'key',
                  2 => 'path',
                  3 => 'type',
                  4 => 'index',
                  5 => 'classname',
                  6 => 'creationdate',
                  7 => 'userowner',
                  8 => 'value',
                  9 => 'class',
                  10 => 'list',
                  11 => 'fullpath',
                  12 => 'childs',
                  13 => 'values',
                  14 => 'cachetag',
                  15 => 'cachetags',
                  16 => 'parent',
                  17 => 'published',
                  18 => 'valuefromparent',
                  19 => 'userpermissions',
                  20 => 'dependencies',
                  21 => 'modificationdate',
                  22 => 'usermodification',
                  23 => 'byid',
                  24 => 'bypath',
                  25 => 'data',
                  26 => 'versions',
                  27 => 'properties',
                  28 => 'permissions',
                  29 => 'permissionsforuser',
                  30 => 'childamount',
                  31 => 'apipluginbroker',
                  32 => 'resource',
                  33 => 'parentClass',
                  34 => 'definition',
                  35 => 'locked',
                  36 => 'language',
                  37 => 'omitmandatorycheck',
                  38 => 'idpath',
                  39 => 'object',
                  40 => 'fieldname',
                  41 => 'property',
                  42 => 'parentid',
                  43 => 'children',
                  44 => 'scheduledtasks',
                ),
                 'blockedVarsForExport' => 
                array (
                ),
              )),
              1 => 
              Pimcore\Model\DataObject\ClassDefinition\Data\ManyToManyObjectRelation::__set_state(array(
                 'fieldtype' => 'manyToManyObjectRelation',
                 'width' => '',
                 'height' => '',
                 'maxItems' => '',
                 'relationType' => true,
                 'visibleFields' => NULL,
                 'allowToCreateNewObject' => true,
                 'optimizedAdminLoading' => false,
                 'enableTextSelection' => false,
                 'visibleFieldDefinitions' => 
                array (
                ),
                 'classes' => 
                array (
                  0 => 
                  array (
                    'classes' => 'OfferToolOfferItem',
                  ),
                ),
                 'pathFormatterClass' => NULL,
                 'name' => 'customItems',
                 'title' => 'Custom Items',
                 'tooltip' => '',
                 'mandatory' => false,
                 'noteditable' => false,
                 'index' => false,
                 'locked' => false,
                 'style' => '',
                 'permissions' => NULL,
                 'datatype' => 'data',
                 'invisible' => false,
                 'visibleGridView' => false,
                 'visibleSearch' => false,
                 'forbiddenNames' => 
                array (
                  0 => 'id',
                  1 => 'key',
                  2 => 'path',
                  3 => 'type',
                  4 => 'index',
                  5 => 'classname',
                  6 => 'creationdate',
                  7 => 'userowner',
                  8 => 'value',
                  9 => 'class',
                  10 => 'list',
                  11 => 'fullpath',
                  12 => 'childs',
                  13 => 'values',
                  14 => 'cachetag',
                  15 => 'cachetags',
                  16 => 'parent',
                  17 => 'published',
                  18 => 'valuefromparent',
                  19 => 'userpermissions',
                  20 => 'dependencies',
                  21 => 'modificationdate',
                  22 => 'usermodification',
                  23 => 'byid',
                  24 => 'bypath',
                  25 => 'data',
                  26 => 'versions',
                  27 => 'properties',
                  28 => 'permissions',
                  29 => 'permissionsforuser',
                  30 => 'childamount',
                  31 => 'apipluginbroker',
                  32 => 'resource',
                  33 => 'parentClass',
                  34 => 'definition',
                  35 => 'locked',
                  36 => 'language',
                  37 => 'omitmandatorycheck',
                  38 => 'idpath',
                  39 => 'object',
                  40 => 'fieldname',
                  41 => 'property',
                  42 => 'parentid',
                  43 => 'children',
                  44 => 'scheduledtasks',
                ),
                 'blockedVarsForExport' => 
                array (
                ),
              )),
            ),
             'locked' => false,
             'blockedVarsForExport' => 
            array (
            ),
             'icon' => NULL,
             'labelWidth' => 100,
             'labelAlign' => 'left',
          )),
        ),
         'locked' => false,
         'blockedVarsForExport' => 
        array (
        ),
      )),
    ),
     'locked' => false,
     'blockedVarsForExport' => 
    array (
    ),
     'icon' => NULL,
     'labelWidth' => 100,
     'labelAlign' => 'left',
  )),
   'icon' => '',
   'previewUrl' => '',
   'group' => 'E-Commerce',
   'showAppLoggerTab' => false,
   'linkGeneratorReference' => '',
   'previewGeneratorReference' => '',
   'compositeIndices' => 
  array (
  ),
   'generateTypeDeclarations' => true,
   'showFieldLookup' => false,
   'propertyVisibility' => 
  array (
    'grid' => 
    array (
      'id' => true,
      'key' => false,
      'path' => true,
      'published' => true,
      'modificationDate' => true,
      'creationDate' => true,
    ),
    'search' => 
    array (
      'id' => true,
      'key' => false,
      'path' => true,
      'published' => true,
      'modificationDate' => true,
      'creationDate' => true,
    ),
  ),
   'enableGridLocking' => false,
   'dao' => NULL,
   'blockedVarsForExport' => 
  array (
  ),
));
